=== lmontejo91/Examen3Evaluacion_LuciaMontejo/EJERCICIO 1. XML/schemaTiempo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- ESTRUCTURA METEREOLOGÍA -->
<xs:element name="metereologia">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="comunidad" minOccurs="0" maxOccurs="unbounded" type="tipo_comunidad"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<!-- ESTRUCTURA COMUNIDAD -->
<xs:complexType name="tipo_comunidad">
    <xs:sequence>
        <xs:element name="nombre" type="tipo_nombre"/>
        <xs:element name="provincia" type="tipo_provincia" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence> 
</xs:complexType>

<!-- ESTRUCTURA PROVINCIA -->
<xs:complexType name="tipo_provincia">
    <xs:sequence>
        <xs:element name="nombre" type="tipo_nombre"/>
        <xs:element name="poblacion" type="tipo_poblacion" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<!-- ESTRUCTURA POBLACIÓN -->
<xs:complexType name="tipo_poblacion">
    <xs:sequence>
        <xs:element name="nombre" type="tipo_nombre"/>
        <xs:element name="prediccion" type="tipo_prediccion" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<!-- ESTRUCTURA PREDICCIÓN -->
<xs:complexType name="tipo_prediccion">
    <xs:sequence>
        <xs:element name="fecha" type="xs:date"/>
        <xs:element name="temp_maxima" type="tipo_temperatura"/>
        <xs:element name="temp_minima" type="tipo_temperatura"/>
        <xs:element name="probabilidad_lluvia" type="tipo_lluvia"/>
        <xs:element name="avisos_riesgo" type="tipo_avisos" minOccurs="0" maxOccurs="10"/>
    </xs:sequence>
</xs:complexType>

<!-- RESTRICCIÓN PARA NOMBRE (se aplica a nombre de comunidad, de provincia y de población) -->
<xs:simpleType name="tipo_nombre">
    <xs:restriction base="xs:string">
        <xs:pattern value="[A-Za-zÀ-ÿ]+(\s[A-Za-zÀ-ÿ]+)*"/>
    </xs:restriction>
</xs:simpleType>

<!-- RESTRICCIÓN PARA TEMPERATURA (se aplica temp_maxima y temp_minima) -->
<xs:simpleType name="tipo_temperatura">
    <xs:restriction base="xs:decimal">
        <xs:minInclusive value="-50"/>
        <xs:maxInclusive value="50"/>
        <xs:fractionDigits value="2"/> <!-- Limita el número de decimales que se pueden poner a dos. -->
    </xs:restriction>
</xs:simpleType>

<!-- RESTRICCIÓN PARA PROBABILIDAD_LLUVIA -->
<xs:simpleType name="tipo_lluvia">
    <xs:restriction base="xs:integer">
        <xs:minInclusive value="0"/>
        <xs:maxInclusive value="100"/>
    </xs:restriction>
</xs:simpleType>

<!-- RESTRICCIÓN PARA AVISOS_RIESGO -->
<xs:simpleType name="tipo_avisos">
    <xs:restriction base="xs:string">
        <xs:pattern value="[vV]iento|[nN]ieve|[tT]ormentas|[hH]uracán"/>
    </xs:restriction>
</xs:simpleType>

</xs:schema>

=== lmontejo91/Examen3Evaluacion_LuciaMontejo/EJERCICIO 1. XML/Ejercicio1.Tiempo_VALIDO.xml
<?xml version="1.0" encoding="UTF-8"?>
<metereologia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="schemaTiempo.xsd">

    <comunidad>
        <nombre>Comunidad de Madrid</nombre>
        <provincia>
            <nombre>Madrid</nombre>
            <poblacion>
                <nombre>Alcobendas</nombre>
                <prediccion>
                    <fecha>2022-05-24</fecha>
                    <temp_maxima>23.52</temp_maxima>
                    <temp_minima>11</temp_minima>
                    <probabilidad_lluvia>3</probabilidad_lluvia>
                    <!-- No hay avisos de riesgo -->
                </prediccion> 
                <prediccion>
                    <fecha>2022-05-23</fecha>
                    <temp_maxima>28</temp_maxima>
                    <temp_minima>15.60</temp_minima>
                    <probabilidad_lluvia>0</probabilidad_lluvia>
                    <!-- No hay avisos de riesgo -->
                </prediccion> 
            </poblacion>
        </provincia>
    </comunidad>

    <comunidad>
        <nombre>Galicia</nombre>
        <provincia>
            <nombre>A coruña</nombre>
            <poblacion>
                <nombre>Muros</nombre>
                <prediccion>
                    <fecha>2022-03-12</fecha>
                    <temp_maxima>12</temp_maxima>
                    <temp_minima>0</temp_minima>
                    <probabilidad_lluvia>90</probabilidad_lluvia>
                    <avisos_riesgo>Nieve</avisos_riesgo> <!-- Acepta con primera letra en mayúscula -->
                    <avisos_riesgo>viento</avisos_riesgo> <!-- También en minúscula -->
                </prediccion>     
            </poblacion>
        </provincia>
    </comunidad>

</metereologia>
